# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pacio
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The PACIO Project is a collaborative effort to advance interoperable health 
  data exchange between post-acute care and other providers, patients, and other 
  key stakeholders across health care and to promote health data exchange 
  in collaboration with policy makers, standards organizations, and industry 
  through a consensus-based approach.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pacioproject.org" # the base hostname & protocol for your site
twitter_username: pacio_project

# Build settings
markdown: kramdown
